version: '3'
services:
    node1:
      build: .
      container_name: "node1"
      networks:
        - black-net
      ports: 
        - "5001:5000"
      volumes:
         - ".:/app"
    node2:
      build: .
      container_name: "node2"
      networks:
        - black-net
      ports: 
        - "5002:5000"
      volumes:
         - ".:/app"

networks:
  black-net:
    driver: bridge
